### ISSUE TITLE
Need a published image for init postgresql database

### ISSUE THREAD

**Issue by skeeey** [open-cluster-management/hub-of-hubs#11]
### Test Environment
- ACM 2.3
- HOH v0.1.0
- Transport Layer: Open Horizon

### Problem
There is no a published image for init postgresql database, so we cannot run [hub-of-hubs-postgresql setup script](https://github.com/open-cluster-management/hub-of-hubs-postgresql/blob/main/pgo/setup.sh) directly, we need to build the image by ourself

### Expected

We have a published image for init postgresql database in the https://quay.io/organization/open-cluster-management-hub-of-hubs

**Comment by vadimeisenbergibm** [comment]
done: https://quay.io/repository/open-cluster-management-hub-of-hubs/hub-of-hubs-postgresql
