### ISSUE TITLE
Failed to uninstall the hub-of-hubs with undeploy_hub_of_hubs.sh

### ISSUE THREAD

**Issue by skeeey** [open-cluster-management/hub-of-hubs#14]
### Test Environment
- ACM 2.3
- HOH v0.1.0
- Transport Layer: Open Horizon

### Problem
We  uninstall the hub-of-hubs with [undeploy_hub_of_hubs.sh](https://github.com/open-cluster-management/hub-of-hubs/blob/main/deploy/undeploy_hub_of_hubs.sh), the uninstall process hangs due to the `configs.hub-of-hubs.open-cluster-management.io` cannot be deleted, we need to remove the `hub-of-hubs.open-cluster-management.io/hoh-config-cleanup ` finalizer  from the hoh config CR manually

### Expected

We can use `undeploy_hub_of_hubs.sh` to uninstall the hoh

**Comment by nirrozenbaum** [comment]
fixed - 
https://github.com/open-cluster-management/hub-of-hubs/commit/92868f2143f1c17b72209aabe8fcb1e4ed97f195
