### ISSUE TITLE
Cannot reconcile back to the original console-chart and grc quickly after undeploying HoH

### ISSUE THREAD

**Issue by clyang82** [open-cluster-management/hub-of-hubs#22]
Cannot reconcile back to the original console-chart and grc quickly after undeploying HoH
https://github.com/open-cluster-management/hub-of-hubs/blob/a91204440645447217d99e9982141ac1ac64e2ec/deploy/undeploy_hub_of_hubs.sh#L13

You may add delete `subscription` as what you have done in deploy hoh script.

/assign @vadimeisenbergibm

**Comment by vadimeisenbergibm** [comment]
@clyang82 

Please note that currently, the work Hub-of-Hubs is done in the following way:

1. Install ACM
2. Deploy Hub-of-Hubs
3. Add Policy/PlacementRule/PlacementBinding CRs
4. Delete Policy/PlacementRule/PlacementBinding CRs
5. Undeploy Hub-of-Hubs
6. Uninstall ACM

The steps 1 and 2, and also 5 and 6, are separated only for the prototype. In production, steps 1 and 2, and 5 and 6, should be the same step, so there will be no meaning to the scenario where you undeploy Hub-of-Hubs and proceed to use vanilla ACM. For the same reason, there is no point in testing steps 1, 3, 2, in this order, or steps 5,6,4.
